### ISSUE TITLE
Exercise 9: Move countries from one box to the other

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JS-Tracks#10]
Create two multiple selection box. First box contains list of countries and when you select a country and click on add button. Selected country will disappear from first box and appear in second button. And when you select a country from second box and click on remove button it will disappear from second box and appear in first box.

https://github.com/ayodeleDD/JS-Tracks/tree/master/Exercise-9

**Comment by segunadeleye** [comment]
You don't need to create new option elements. You can simply get the selected options and move them.

**Comment by ayodeleopetumo** [comment]
Code improved

**Comment by segunadeleye** [comment]
Looks good
