### ISSUE TITLE
Exercise 12: Domain/Sub-domain Matching 

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JS-Tracks#11]
Create a simple form with a textfield and a submit button. When I enter a URL in this textfield and submit the form, it should alert me the domain name from the entered url. For example, If I enter: 1. http://example.com/folder/file.html, then on submitting the form it should alert something like: Domain: example.com. 2. (with subdomain) http://vinsol.example.com/folder/file.html, then on submitting the form it should alert something like: Domain: example.com, Subdomain: vinsol. Basic Idea is to extract
domain name and subdomain from a URL. Note: Use Regular Expressions for this exercise. Please use only Object oriented approach to write your code.

https://github.com/ayodeleDD/JS-Tracks/blob/master/Exercise-12/Exercise-12.js

**Comment by segunadeleye** [comment]
Why do you need test regex and extract regex? Can't we use extract to also test?

**Comment by ayodeleopetumo** [comment]
Because they contain different expressions. While we can use the `urlExtractPattern` to test, it doesn't quite behave how it is supposed to, hence the need for `urlTestPattern`.
