### ISSUE TITLE
Exercise 2: Check all or none

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JS-Tracks#2]
Create a list of checkbox (red, green, yellow, white, black). Now create two links "Check all" and 'none'. When you click on check all link all checkbox will be selected, and when you click on none link all checkbox will be deselected(working example is gmail).

https://github.com/ayodeleDD/JS-Tracks/tree/master/Exercise-2

**Comment by segunadeleye** [comment]
1. Checkboxes cannot have the same name. Replicate this in other exercises.
2. You don't have to store `this.checkboxes` in a variable again.
3. Always use DRY approach. You can have just one method handle checking and unchecking all boxes.

**Comment by ayodeleopetumo** [comment]
Issues fixed

**Comment by segunadeleye** [comment]
Good
