### ISSUE TITLE
Exercise 4: Parent Checkbox and their children checkbox

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JS-Tracks#4]
Create a div with height 100 and scroll bars. Display a list of checkbox color, drinks, movies and bikes in this div. Now when you click on color checkbox it should display four checkboxes(red, yellow, green, blue) as a child list and color checkbox should be checked with its child list of checkboxes. Again when you click on color checkbox child list should be hidden and its child checkboxes should get deselected(clear state). Same with movies, drink and bikes. Movies: [Dar, Sir] Drinks: [coke, pepsi, dew] Bikes: [Vrod, pulsar, cbz]. Remember: When you click on a parent checkbox and if child list checkboxes are out of visible area the div's scrollbars should scroll and child list should be visible automatically. We should not scroll the div to see them(child list of checkboxes).

https://github.com/ayodeleDD/JS-Tracks/tree/master/Exercise-4

**Comment by segunadeleye** [comment]
I must commend you for the way you have implemented this :+1: :clap: . Just some few things to fix. 
1. Don't use abbreviations for variable.
2. You can use a different varible name instead of `visibility`.
3. Use proper naming convention for class name

**Comment by ayodeleopetumo** [comment]
Issues Fixed

**Comment by segunadeleye** [comment]
Looks good.
