### ISSUE TITLE
Exercise 6: Form Validation Using JS

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JS-Tracks#5]
Create a form like https://www.dropbox.com/s/qccm98brx2hdbrw/Form_validation.png and add JS validations to that form.When you click on 'Go' JS will check all text fields, and give an alert like "Login Id can't be empty". One alert per empty field. For textarea it should check for empty and min length of 50 characters.If any field is invalid then it should not submit the form. Also It should also confirm "receive notification"

https://github.com/ayodeleDD/JS-Tracks/tree/master/Exercise-6

**Comment by segunadeleye** [comment]
Nicely structured. However;
1. You should not prevent default for each validation. You can check for one thing and prevent default based on that.
2. Let's have separate generic methods that handle validation. These methods should return true or false. You can discuss this if you have any doubt.
3. Your validation does not account for blank spaces.
