### ISSUE TITLE
Exercise 10: Email and URL Format Validation

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JS-Tracks#6]
The form you create like https://www.dropbox.com/s/qccm98brx2hdbrw/Form_validation.png. Add validations for the correct format of email and homepage(url) using regular expressions. Please use only Object oriented approach to write your code.

https://github.com/ayodeleDD/JS-Tracks/tree/master/Exercise-10

**Comment by segunadeleye** [comment]
1. You should not prevent default event for each validation. You can check for one thing and prevent default based on that.
2. Let's have separate generic methods that handle validation. These methods should return true or false. You can discuss this if you have any doubt.
3. Your validation does not check blank spaces.
