### ISSUE TITLE
Exercise 7: Name input in Alert and Welcome in page content

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JS-Tracks#8]
Create a HTML page, when it opens in Browser, it should prompt twice. Once for first name and second for last name. When you enter first and last name, it should alert you as "Hello firstname lastname."After alert it should put that text in html page.Note: Keep in mind when you take inputs from users, always consider cases where user has entered null or blank values(few white spaces). User may pressed ESC button. In such cases you should not accept the input.

https://github.com/ayodeleDD/JS-Tracks/tree/master/Exercise-7

**Comment by segunadeleye** [comment]
1. Why have you used a load event?
2. It asks for lastname even if the firstname field is empty. It should only show the lastname prompt if and only if the firstname prompt is filled.
3. It allows blank spaces. This should not be so.
4. Let's have a different method that displays the message.

**Comment by segunadeleye** [comment]
You do not need the `if` statement within the first `do-while` statement. The next `do-while` will not be executed until the first `do-while` passes.

**Comment by ayodeleopetumo** [comment]
Fixed

**Comment by segunadeleye** [comment]
Looks good.

**Comment by ayodeleopetumo** [comment]
Code improved
