### ISSUE TITLE
Exercise 8: Input URL and open it

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JS-Tracks#9]
Write a Script that prompts you for a URL. If the input is an empty url it should alert you. Otherwise it should open that URL in a new window of width 400px and height 450px, without any type of bar(status bar, scroll bars etc..).

https://github.com/ayodeleDD/JS-Tracks/tree/master/Exercise-8

**Comment by segunadeleye** [comment]
1. You don't need a load event handler.
2. Make `windowFeatures` an instance variable.
